services:
  # Backend API service
  - type: web
    name: clarity-legal-backend
    runtime: node
    rootDir: backend
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NODE_ENV
        value: production
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health